name: Qt Build
# .github/workflows/qt-build.yml

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Clean Qt directory
        run: |
          if [ -d "/home/runner/work/plug-in-pool-2025/Qt" ]; then
            rm -rf /home/runner/work/plug-in-pool-2025/Qt
          fi

      - name: Install Qt
        run: |
          attempt=0
          max_attempts=3
          while [ $attempt -lt $max_attempts ]; do
            attempt=$((attempt + 1))
            if jurplel/install-qt-action@v2 --version "5.12.8" --host "linux" --target "desktop"; then
              break
            else
              sleep 10
            fi
          done

          if [ $attempt -eq $max_attempts ]; then
            exit 1
          fi

      - name: Run qmake
        run: |
          cd plug-in-pool-visualisation && qmake

      - name: Run make
        run: |
          cd plug-in-pool-visualisation && make
