name: Qt Build
# .github/workflows/qt-build.yml

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.12.8"
          host: "linux"
          target: "desktop"
          setup-python: false

      - name: Run qmake
        run: |
          cd plug-in-pool-visualisation && qmake

      - name: Run make
        run: |
          cd plug-in-pool-visualisation && make
